### ISSUE TITLE
Can't see cursor on terminal when using theme

### ISSUE THREAD

**Issue by ryan-zayne** [u1145h/vscode-theme#1]
For the reason, the big white blinking cursor disappears from the vscode integrated terminal when using this theme

![image](https://github.com/user-attachments/assets/ae82cbca-5eed-4d92-83be-526df85af90a)

**Comment by u1145h** [comment]
Thank you for your feedback 🫠. I recently pushed an update that includes some color fixes also includes the Terminal Cursor Color issue. Do let me know if you find any other issues. I will try to fix those as soon as I can.
![20240827_03h06m07s_grim](https://github.com/user-attachments/assets/4bdf136d-1723-4a16-a952-eae32069a9ed)

**Comment by ryan-zayne** [comment]
> Thank you for your feedback 🫠. I recently pushed an update that includes some color fixes also includes the Terminal Cursor Color issue. Do let me know if you find any other issues. I will try to fix those as soon as I can. ![20240827_03h06m07s_grim](https://private-user-images.githubusercontent.com/78568197/361583617-4bdf136d-1723-4a16-a952-eae32069a9ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MTMxNzQsIm5iZiI6MTcyNDcxMjg3NCwicGF0aCI6Ii83ODU2ODE5Ny8zNjE1ODM2MTctNGJkZjEzNmQtMTcyMy00YTE2LWE5NTItZWFlMzIwNjlhOWVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDIyNTQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlNTk4ZDllNzViZDk4MGMwOWE3NGY0MmQzNTZkM2M4YTZjNmE4MzFlOGZlYWNhMjE1ODMyMmUzNjVlMTU0MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LoRBgSx_8OVne9iTAI8hokpOzG4sirBqx9w39ETgGfE)

Thanks!
